/**
 * Human labels for the SATCAT codes that appear most; anything else is shown as its code.
 * Source: CelesTrak SATCAT documentation (owner and launch-site tables).
 */

export const OWNER_LABELS: Record<string, string> = {
  US: 'United States',
  PRC: 'China',
  CIS: 'Russia / CIS',
  ESA: 'European Space Agency',
  UK: 'United Kingdom',
  JPN: 'Japan',
  IND: 'India',
  FR: 'France',
  GER: 'Germany',
  CA: 'Canada',
  ITA: 'Italy',
  SKOR: 'South Korea',
  ISRA: 'Israel',
  AUS: 'Australia',
  ARGN: 'Argentina',
  BRAZ: 'Brazil',
  SPN: 'Spain',
  NETH: 'Netherlands',
  NOR: 'Norway',
  SWED: 'Sweden',
  TURK: 'Türkiye',
  UAE: 'United Arab Emirates',
  SES: 'SES (Luxembourg)',
  EUTE: 'Eutelsat',
  IM: 'Inmarsat',
  ORB: 'Orbcomm',
  GLOB: 'Globalstar',
  IRID: 'Iridium',
  O3B: 'O3b Networks',
  EUME: 'EUMETSAT',
  ITSO: 'Intelsat',
  ISS: 'ISS partners',
  TWN: 'Taiwan',
  LUXE: 'Luxembourg',
  FIN: 'Finland',
  POL: 'Poland',
  DEN: 'Denmark',
  SAFR: 'South Africa',
  IRAN: 'Iran',
  NKOR: 'North Korea',
  PAKI: 'Pakistan',
  EGYP: 'Egypt',
  INDO: 'Indonesia',
  THAI: 'Thailand',
  MALA: 'Malaysia',
  SING: 'Singapore',
  ASRA: 'Austria',
  BEL: 'Belgium',
  SWTZ: 'Switzerland',
  CZCH: 'Czechia',
  HUN: 'Hungary',
  UKR: 'Ukraine',
  KAZ: 'Kazakhstan',
  MEX: 'Mexico',
  CHLE: 'Chile',
  PER: 'Peru',
  NZ: 'New Zealand',
  QAT: 'Qatar',
  SAUD: 'Saudi Arabia',
  ALG: 'Algeria',
  MA: 'Morocco',
  NIG: 'Nigeria',
  VENZ: 'Venezuela',
  BOL: 'Bolivia',
  AB: 'Arab Satellite Communications Org.',
  AC: 'Asia Satellite Telecom',
  NATO: 'NATO',
  RASC: 'RascomStar',
};

export const LAUNCH_SITE_LABELS: Record<string, string> = {
  AFETR: 'Cape Canaveral / KSC, USA',
  AFWTR: 'Vandenberg, USA',
  TYMSC: 'Baikonur, Kazakhstan',
  PLMSC: 'Plesetsk, Russia',
  VOSTO: 'Vostochny, Russia',
  XICLF: 'Xichang, China',
  JSC: 'Jiuquan, China',
  TAISC: 'Taiyuan, China',
  WENSC: 'Wenchang, China',
  FRGUI: 'Kourou, French Guiana',
  SRILR: 'Satish Dhawan, India',
  TANSC: 'Tanegashima, Japan',
  KSCUT: 'Uchinoura, Japan',
  WLPIS: 'Wallops Island, USA',
  KODAK: 'Kodiak, Alaska, USA',
  RLLB: 'Mahia, New Zealand',
  SEAL: 'Sea Launch (Odyssey platform)',
  YSLA: 'Yellow Sea platform, China',
  SVOBO: 'Svobodny, Russia',
  DLS: 'Dombarovsky, Russia',
  PKMTR: 'Palmachim, Israel',
  NSC: 'Naro, South Korea',
  SEM: 'Semnan, Iran',
  SNMLP: 'San Marco platform, Kenya',
  HGSTR: 'Hammaguira, Algeria',
  WOMRA: 'Woomera, Australia',
  ERAS: 'Air launch (Pegasus)',
  VOLO: 'Air launch (Vertical)',
  SUBL: 'Submarine launch',
};

export const OPS_STATUS_LABELS: Record<string, string> = {
  '+': 'Operational',
  '-': 'Nonoperational',
  P: 'Partially operational',
  B: 'Backup / standby',
  S: 'Spare',
  X: 'Extended mission',
  D: 'Decayed',
  '?': 'Unknown',
  '': 'Not stated',
};

export const RCS_LABELS: Record<string, string> = {
  SMALL: 'Small (< 0.1 m²)',
  MEDIUM: 'Medium (0.1–1 m²)',
  LARGE: 'Large (> 1 m²)',
  '': 'Not published',
};

export function ownerLabel(code: string): string {
  return OWNER_LABELS[code] ?? code ?? '—';
}

export function launchSiteLabel(code: string): string {
  return LAUNCH_SITE_LABELS[code] ?? code ?? '—';
}
